### PR TITLE
Revert "[DPTOOLS-745] Reset backfill dagrun to failed"

### PR DESCRIPTION
**Pull request by feng-tao**
The change somehow doesn't seem to work on tars. Revert it(https://github.com/lyft/incubator-airflow/pull/87/files) for now and investigate later.

### CODE REVIEW

**Comment by feng-tao** [comment]
👀 @milton0825 @astahlman @ArgentFalcon

**Comment by ArgentFalcon** [comment]
Just a revert right?
👍

**Comment by ArgentFalcon** [comment]
uhh, @feng-tao tests are failing.

**Comment by feng-tao** [comment]
@ArgentFalcon , so far not planning to revert yet. I found out that my last week's issue is due to something else not this one.

**Pull request closed without merging**
