### PR TITLE
test lyft logger

### PR DESCRIPTION
**Pull request by youngyjd**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by jinhyukchang** [comment]
@youngyjd Agreed with @astahlman unless we have really good reason to introduce lyft logger.  Once introduced, it can easily spread out, and would make version upgrade harder. Could you tell us what lyft logger will bring here?

**Comment by youngyjd** [comment]
@jinhyukchang https://github.com/lyft/python-lyft-logging#dos kv will become json fields in Kibana which is easier to search.

**Comment by astahlman** [comment]
@youngyjd Would it actually be that much easier though? It seems like it would be just as easy to query for a string like "Cleared task: <task-id>" or "Cleared task: .* in DAG <dag-id>" as to search for a kv pair. Actually, I'm not even sure what a query for the kv pairs would look like

**Comment by youngyjd** [comment]
@astahlman yeah. I am thinking about how we search it without KV. I will remove lyft-logging library 👌

**Pull request closed without merging**
