### PR TITLE
Upgrade to python 3.6

### PR DESCRIPTION
**Pull request by milton0825**
Upgrade to python 3.6 since python3 at Lyft is 3.6+

### CODE REVIEW

**Comment by milton0825** [comment]
@astahlman @ArgentFalcon @youngyjd

**Comment by astahlman** [comment]
👍 Well that was easy

**Comment by ArgentFalcon** [comment]
Can we aim this at airflowinfra branch? I think that's the branch that airflowinfra uses.

**Comment by milton0825** [comment]
@ArgentFalcon I think the plan is to upgrade the etl repo in place to PY3 without upgrading airflow versions. I believe airflowinfra is already on 3.6 based on https://github.com/lyft/incubator-airflow/blob/airflowinfra/.travis.yml#L29

**Comment by ArgentFalcon** [comment]
Oh, I see, thanks for clairfying

**Pull request merged**
