### PR TITLE
log celery subprocess errors

### PR DESCRIPTION
**Pull request by youngyjd**
This PR is to improve the logging according to https://github.com/lyft/incubator-airflow/blob/0c941b98020f881e6a3ae49dd4ab9ac40783d3fb/airflow/executors/celery_executor.py#L70

### CODE REVIEW

**Comment by youngyjd** [comment]
@milton0825

**Comment by milton0825** [comment]
👍

**Comment by youngyjd** [comment]
💨

**Comment by milton0825** [comment]
Does 💨 work here?

**Comment by youngyjd** [comment]
@milton0825 I think no. 👀 does not work either. Typed 💨 out of habit...

**Comment by youngyjd** [comment]
two errors in travis build:
```
======================================================================
ERROR: mysql_hook_test_bulk_load (tests.MySqlTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/lyft/incubator-airflow/tests/operators/operators.py", line 80, in mysql_hook_test_bulk_load
    with h.get_conn() as c:
AttributeError: __exit__
-------------------- >> begin captured logging << --------------------
root: INFO: Using connection to: localhost
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_overwrite_schema (tests.MySqlTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/lyft/incubator-airflow/tests/operators/operators.py", line 131, in test_overwrite_schema
    from _mysql_exceptions import OperationalError
ImportError: No module named _mysql_exceptions
```

Unrelated to this PR but we need to fix it later.

**Pull request merged**
