### PR TITLE
[AIRFLOW-1472] Fix SLA misses triggering on skipped tasks.

### PR DESCRIPTION
**Pull request by astahlman**
Cherry-pick fix for https://issues.apache.org/jira/browse/AIRFLOW-1472

### CODE REVIEW

**Comment by astahlman** [comment]
cc @lyft/dpe-airflow

**Comment by astahlman** [comment]
@mik-laj this is a cherry-pick of an [upstream PR](https://github.com/apache/airflow/pull/3370) that was merged >2 years ago. Looks like it was originally merged without unit tests, unfortunately

**Comment by kaxil** [comment]
Yea I think I had tried it out and works fine

**Comment by kaxil** [comment]
Looks like unfortunately, we haven't included it in any point releases

**Pull request merged**
