### PR TITLE
Pull [AIRFLOW-1157] Fix missing pools crashing the scheduler

### PR DESCRIPTION
**Pull request by feng-tao**
Pull https://github.com/apache/incubator-airflow/pull/3002 into repo.

I did it manually as cherry doesn't work(too many things have been changed even the function name has changed...)

### CODE REVIEW

**Comment by feng-tao** [comment]
👀 @lyft/dp-tools-viz

**Comment by feng-tao** [comment]
👀 @ArgentFalcon @astahlman @youngyjd

**Comment by astahlman** [comment]
:+1:

**Comment by feng-tao** [comment]
💨

**Pull request merged**
