### PR TITLE
[AIRFLOW-1519] Add server side paging in DAGs list

### PR DESCRIPTION
**Pull request by Alagappan**
Airflow's main page previously did paging client-side via a jQuery plugin (DataTable) which was very slow at loading all DAGs. The browser would load all DAGs in the table.
The result was performance degradation when having
a number of DAGs in the range of 1K.

This commit implements server-side paging using the webserver page
size setting, sending to the browser only the elements for the specific page.

Closes #2531 from edgarRd/erod-ui-dags-paging

# Conflicts:
#	airflow/www/views.py

### CODE REVIEW

**Comment by Alagappan** [comment]
:eyes: @astahlman #dp-tools

**Comment by astahlman** [comment]
:+1:

Looks good, assuming it works in devbox

**Comment by Alagappan** [comment]
There was an issue with PAGE_SIZE global variable not being defined in views.py. Found the relevant change and fixed it manually. `git merge` instead of `git cherry-pick` touches a lot of files.

**Comment by astahlman** [comment]
+1

**Comment by Alagappan** [comment]
💨

**Pull request merged**
