### PR TITLE
Add prev_ds_nodash and next_ds_nodash macro

### PR DESCRIPTION
**Pull request by feng-tao**
Context: https://lyft.slack.com/archives/CA4HS7D8V/p1535567521000100

### CODE REVIEW

**Comment by feng-tao** [comment]
👀 @milton0825 @wanyifulyft @AndrewMLewis

**Comment by feng-tao** [comment]
cc @lyft/dp-tools-viz

**Comment by wanyifulyft** [comment]
+1

**Comment by wanyifulyft** [comment]
Great! This will help a ton in applying prev_ds to the dimensional table.

**Pull request merged**
