### PR TITLE
update SSHHook to latest

### PR DESCRIPTION
**Pull request by milton0825**
Cherry pick new ssh hook and ssh operator based on paramiko from upstream.

https://issues.apache.org/jira/browse/AIRFLOW-756
https://github.com/apache/incubator-airflow/pull/1999

### CODE REVIEW

**Comment by milton0825** [comment]
@lyft/dp-tools-viz

**Comment by feng-tao** [comment]
it seems this sshHook is backward incompatible. Do you know whether there are any dags depend on sshHook currently at etl repo?

**Comment by milton0825** [comment]
@feng-tao no one is using the SSHHook in etl

**Comment by feng-tao** [comment]
👍

**Comment by feng-tao** [comment]
so I am curious what's your plan for using the SSHHook? Is it for tars?

**Comment by milton0825** [comment]
I am planning to use it to build `HiveToSFTPOperator`. Data engineers have usecases that they will fetch data from Hive and upload it to third-party SFTP site.

**Pull request merged**
