### PR TITLE
Reapply socket patch

### PR DESCRIPTION
**Pull request by FLutikoff**
Patch 1.9.0-modified with commit: https://github.com/lyft/incubator-airflow/commit/dd6479c7d4199ad43976d99968c06d2972d3b161

### CODE REVIEW

**Comment by astahlman** [comment]
Looks fine to me, but you'll probably want a +1 from someone your team, too.

**Comment by FLutikoff** [comment]
meow @ArgentFalcon @jimcchiang

**Comment by jimcchiang** [comment]
👍

**Comment by FLutikoff** [comment]
🔨

**Comment by FLutikoff** [comment]
💨

**Pull request merged**
