### PR TITLE
[AIRFLOW-1397][AIRFLOW-1] No Last Run column data displyed in Airflow…

### PR DESCRIPTION
**Pull request by Alagappan**
… UI 1.8.1

Closes #2430 from preete-dixit-ck/master

### CODE REVIEW

**Comment by Alagappan** [comment]
:eyes: @astahlman @shenghuy

**Comment by astahlman** [comment]
+1

**Comment by shenghuy** [comment]
+1

**Comment by astahlman** [comment]
:dash:

**Pull request merged**
