### PR TITLE
Fix attribute not found

### PR DESCRIPTION
**Pull request by milton0825**
```
Traceback (most recent call last):
  File "/code/venvs/venv/bin/airflow", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/code/venvs/venv/src/apache-airflow/airflow/bin/airflow", line 37, in <module>
    args.func(args)
  File "/code/venvs/venv/src/apache-airflow/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
  File "/code/venvs/venv/src/apache-airflow/airflow/bin/cli.py", line 759, in test
    ti.run(ignore_task_deps=True, ignore_ti_state=True, test_mode=True)
  File "/code/venvs/venv/src/apache-airflow/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/code/venvs/venv/src/apache-airflow/airflow/models/taskinstance.py", line 1085, in run
    session=session)
  File "/code/venvs/venv/src/apache-airflow/airflow/utils/db.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/code/venvs/venv/src/apache-airflow/airflow/models/taskinstance.py", line 926, in _run_raw_task
    context = self.get_template_context()
  File "/code/venvs/venv/src/apache-airflow/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/code/venvs/venv/src/apache-airflow/airflow/models/taskinstance.py", line 1281, in get_template_context
    class VariableAccessor:
  File "/code/venvs/venv/src/apache-airflow/airflow/models/taskinstance.py", line 1303, in VariableAccessor
    default_var=Variable._Variable__NO_DEFAULT_SENTINEL,
AttributeError: type object 'BaseVariable' has no attribute '_Variable__NO_DEFAULT_SENTINEL'
```

---
Issue link: WILL BE INSERTED BY [boring-cyborg](https://github.com/kaxil/boring-cyborg)

Make sure to mark the boxes below before creating PR: [x]

- [ ] Description above provides context of the change
- [ ] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [ ] Unit tests coverage for changes (not needed for documentation changes)
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions.
- [ ] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by milton0825** [comment]
@astahlman @feng-tao @ArgentFalcon

**Comment by astahlman** [comment]
👍

**Comment by feng-tao** [comment]
+1
curious where do you get the log? I recalled we didn't find much info yesterday?

**Comment by milton0825** [comment]
I was only able to gather the log while testing locally.

**Pull request merged**
