### PR TITLE
cherry pick a8174047b24ec4c3eb62e5651b39ca44dc8dd94b

### PR DESCRIPTION
**Pull request by youngyjd**
Cherry pick a8174047b24ec4c3eb62e5651b39ca44dc8dd94b to get more information on subprocess logging

### CODE REVIEW

**Comment by youngyjd** [comment]
👀 @astahlman @milton0825 @feng-tao 

P.S. How to solve this?
```CLA check — The following authors related to commits in this PR have not signed the CLA: johnarnold```

**Comment by astahlman** [comment]
👍 Not sure about the CLA check

**Comment by milton0825** [comment]
👍

**Comment by youngyjd** [comment]
@milton0825 I have no context, but is there any reason you have to change the `subprocess.check_call` to `subprocess.check_output` in https://github.com/lyft/incubator-airflow/commit/4260271569a1b0d8eea994ab5c0e1b0b92aa7f77 ? Don't want to merge this one to accidentally revert the things you have done.

**Comment by feng-tao** [comment]
👍  you could check the commit message author to you which I assume should solve the cla issue.

**Comment by milton0825** [comment]
Ah I think we need to use `check_output` here. I am redirecting the `STDOUT` in to the logger to make backfill progress bar works.

**Comment by youngyjd** [comment]
@milton0825 👍 I will just close one and bring a new PR in.

**Comment by youngyjd** [comment]
https://github.com/lyft/incubator-airflow/pull/120 instead

**Pull request closed without merging**
