### PR TITLE
[DPTOOLS-2681]Cherry pick pool with yaml file

### PR DESCRIPTION
**Pull request by sherryzhao1006**
---
https://jira.lyft.net/browse/DPTOOLS-2681
Cherry-pick the changes: https://github.com/lyft/incubator-airflow/pull/51  and https://github.com/lyft/incubator-airflow/pull/90 from data-platform-upgrade branch to add "pools" cmd in cli.

### CODE REVIEW

**Comment by sherryzhao1006** [comment]
👀 @youngyjd @feng-tao @astahlman

**Comment by youngyjd** [comment]
@sherryzhao1006 Did you test out whether this cherrypick still work as well, since there may be some changes in cli.py between data-platform-upgrade and airflowinfra branch. You may use the SHA in this branch and test it out in devbox?

**Comment by sherryzhao1006** [comment]
> @sherryzhao1006 Did you test out whether this cherrypick still work as well, since there may be some changes in cli.py between data-platform-upgrade and airflowinfra branch. You may use the SHA in this branch and test it out in devbox?

Yes. I tested this in devbox in airflowinfra.legacy. I'm planning to send out the PR in airflowinfra after I fix the build error here.

**Comment by youngyjd** [comment]
@sherryzhao1006 Awesome! This seems to be the error 
```
airflow/bin/cli.py:348:13: E125 continuation line with same indent as next logical line
```

**Comment by sherryzhao1006** [comment]
> @sherryzhao1006 Awesome! This seems to be the error
> 
> ```
> airflow/bin/cli.py:348:13: E125 continuation line with same indent as next logical line
> ```
> 
> Please also squash all commits into one before merging

Still fixing.
Yep. Will squash.

**Comment by youngyjd** [comment]
👍

**Pull request merged**
