### PR TITLE
Sync from upstream

### PR DESCRIPTION
**Pull request by ArgentFalcon**
Ran `git pull upstream master` on our master branch, trying to pull all the latest commits from upstream to make work easier

### CODE REVIEW

**Comment by ArgentFalcon** [comment]
👀 @youngyjd @milton0825 @astahlman 
cc @lyft/dp-tools-viz

**Comment by ArgentFalcon** [comment]
This is just master -> master. So that it's easier to work off of it for upstreamable work.

**Comment by ArgentFalcon** [comment]
Though maybe I should just do that from my personal fork.

**Comment by ArgentFalcon** [comment]
Also, I would like to try to upgrade our version of airflow to 10.10. How do you feel about that?

**Comment by youngyjd** [comment]
@ArgentFalcon I would vote for it if you have bandwidth. Even it is a minor version upgrade, something may be broken and needs to be fixed in a short time period. Zippy is using the cluster for production work with strict SLA.

**Comment by ArgentFalcon** [comment]
Fair. I'll try to wrap up what I'm doing and do it

**Comment by milton0825** [comment]
👍

**Pull request closed without merging**
