### PR TITLE
[DATAHELP-2099] Fix find all downstream skippable duplicates

### PR DESCRIPTION
**Pull request by youngyjd**
This PR is aiming to filter out duplicate TIs when iterating through all downstream tasks.

### CODE REVIEW

**Comment by youngyjd** [comment]
@ArgentFalcon @jinhyukchang

**Comment by youngyjd** [comment]
Will add tests

**Comment by youngyjd** [comment]
🔒

**Comment by ArgentFalcon** [comment]
I'm really curious why we had these issues in the first place. I wonder if it's in the design of
|-->B--|
|         ╲╱
A           D --> E 
|            ^
|-->C--|

And then D and E get repeated twice?

**Comment by youngyjd** [comment]
@ArgentFalcon 
it is this situation
```
a -> b -> d
a -> c -> d
```
When we try to find all skippable downstreams of a, it will result in [b, d, c, d]. However, it should only be [b, c, d].

Tests added.

**Comment by ArgentFalcon** [comment]
Yeah, cool, that's what I was guessing, but yours is a bit more readable.

**Comment by ArgentFalcon** [comment]
👍

**Comment by youngyjd** [comment]
```
test_trigger_dag (tests.www.api.experimental.test_kerberos_endpoints.ApiKerberosTests) ... FAIL
```
Only this one failed tests sometimes, which is unrelated to this change.

**Comment by ArgentFalcon** [comment]
Can you link this PR in the JIRA ticket?

**Pull request merged**
