### PR TITLE
[DATAHELP-120] handle date arrays returned by execution_date_fn correctly

### PR DESCRIPTION
**Pull request by vijaysbhat**
According to the documentation for ExternalTaskSensor, execution_date_fn can return an array of dates to query the metastore for. The currently implemented query doesn't handle arrays correctly and fails.

Porting over the correct implementation from Apache Airflow - https://github.com/apache/incubator-airflow/blob/master/airflow/sensors/external_task_sensor.py#L93

### CODE REVIEW

**Comment by vijaysbhat** [comment]
@lyft/dp-tools-viz

**Comment by astahlman** [comment]
Can you update the PR to use the branch `data-platform-upgrade` as the merge base? This repo is non-standard in that Data Platform doesn't work off of master (there are multiple teams at Lyft that run Airflow instances, and we don't all use the same version)

**Comment by feng-tao** [comment]
another question is that does the patch exist in upstream airflow repo?

**Comment by vijaysbhat** [comment]
@feng-tao yes it does, that's the link I have in the PR description - from upstream Airflow.

**Comment by vijaysbhat** [comment]
@astahlman changing the merge base caused too many conflicts. I'm gonna redo the PR off of data-platform-upgrade

**Pull request closed without merging**
